# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: anna istomina - ux designer
email: istomina.anna@gmail.com
description: This is my design portofio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://annaistomina.com" # the base hostname & protocol for your site
exclude:
  # - "school"
  - ".git"

# Build settings
markdown: kramdown
